### ISSUE TITLE
MySQL auto increment primary key

### ISSUE THREAD

**Issue by AmaVic** [perak/mysql-shadow#6]
Hello, 
I'm currently developing a meteor app using mysql-shadow. In my MySQL database, I have an "id" field which is automatically incremented. When I insert a row (through a mongo collection) in the MySQL database, the new row gets it's id automatically attributed and everything is fine with that.

Where my problem comes is that in the Mongo collection, there is no "id" field (I'm talking about the id in the MySQL database, not the mongo db uuid) since the document I inserted didn't contain such a field. 

My question is the following: is there a particular way to get this id after having inserted the document ? Is there a way to force mysql-shadow to rerun the MySQL to Mongo copy phase runned at startup ?

I have tryied the function "MySQLShadowSyncTable" but it didn't seem to work.

Thanks in advance !

**Comment by perak** [comment]
Hey Victor,

I made that package for one specific project and I needed that just for read-only copy of mySQL database. This is why this package is not best solution for application that read and **write** into mySQL. After record is inserted, triggers can execute and modify many other tables (not ony ID in this table) - that is complex to solve (especially if you have multiple concurent users). Also, there is no reactivity - if data in mySQL is changed from external application - that doesn't reflects until next "shadowSync". So, my suggestion to you is not to use it for anything serious.

But, if you really want to play with it, you can modify package - add code that reads `ID` after `INSERT`. I wish to help you with that, but I cannot - because I am bussy with other things. Let me know if you made something cool :)

**Comment by AmaVic** [comment]
Thanks for your answer ! 
I'm not very familiar with the way packages work (I know how to download one or remove it but that's it) but I might give it a shot if I find some time to do it. If I do, I'll let you know !

In the meantime I think I will follow your advice and not use that package for my application.

Thanks a lot !

**Comment by perak** [comment]
:+1:
